export const NATIONALITY_CHOICES = [
    { code: 'Afghanistan', label: 'Afghanistan' },
    { code: 'Albania', label: 'Albania' },
    { code: 'Algeria', label: 'Algeria' },
    { code: 'Andorra', label: 'Andorra' },
    { code: 'Angola', label: 'Angola' },
    { code: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
    { code: 'Argentina', label: 'Argentina' },
    { code: 'Armenia', label: 'Armenia' },
    { code: 'Australia', label: 'Australia' },
    { code: 'Austria', label: 'Austria' },
    { code: 'Azerbaijan', label: 'Azerbaijan' },
    { code: 'Bahamas', label: 'Bahamas' },
    { code: 'Bahrain', label: 'Bahrain' },
    { code: 'Bangladesh', label: 'Bangladesh' },
    { code: 'Barbados', label: 'Barbados' },
    { code: 'Belarus', label: 'Belarus' },
    { code: 'Belgium', label: 'Belgium' },
    { code: 'Belize', label: 'Belize' },
    { code: 'Benin', label: 'Benin' },
    { code: 'Bhutan', label: 'Bhutan' },
    { code: 'Bolivia', label: 'Bolivia' },
    { code: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
    { code: 'Botswana', label: 'Botswana' },
    { code: 'Brazil', label: 'Brazil' },
    { code: 'Brunei', label: 'Brunei' },
    { code: 'Bulgaria', label: 'Bulgaria' },
    { code: 'Burkina Faso', label: 'Burkina Faso' },
    { code: 'Burundi', label: 'Burundi' },
    { code: 'Cambodia', label: 'Cambodia' },
    { code: 'Cameroon', label: 'Cameroon' },
    { code: 'Canada', label: 'Canada' },
    { code: 'Cape Verde', label: 'Cape Verde' },
    { code: 'Central African Republic', label: 'Central African Republic' },
    { code: 'Chad', label: 'Chad' },
    { code: 'Chile', label: 'Chile' },
    { code: 'China', label: 'China' },
    { code: 'Colombia', label: 'Colombia' },
    { code: 'Comoros', label: 'Comoros' },
    { code: 'Congo', label: 'Congo' },
    { code: 'Costa Rica', label: 'Costa Rica' },
    { code: 'Croatia', label: 'Croatia' },
    { code: 'Cuba', label: 'Cuba' },
    { code: 'Cyprus', label: 'Cyprus' },
    { code: 'Czech Republic', label: 'Czech Republic' },
    { code: 'Denmark', label: 'Denmark' },
    { code: 'Djibouti', label: 'Djibouti' },
    { code: 'Dominica', label: 'Dominica' },
    { code: 'Dominican Republic', label: 'Dominican Republic' },
    { code: 'Ecuador', label: 'Ecuador' },
    { code: 'Egypt', label: 'Egypt' },
    { code: 'El Salvador', label: 'El Salvador' },
    { code: 'Equatorial Guinea', label: 'Equatorial Guinea' },
    { code: 'Eritrea', label: 'Eritrea' },
    { code: 'Estonia', label: 'Estonia' },
    { code: 'Eswatini', label: 'Eswatini' },
    { code: 'Ethiopia', label: 'Ethiopia' },
    { code: 'Fiji', label: 'Fiji' },
    { code: 'Finland', label: 'Finland' },
    { code: 'France', label: 'France' },
    { code: 'Gabon', label: 'Gabon' },
    { code: 'Gambia', label: 'Gambia' },
    { code: 'Georgia', label: 'Georgia' },
    { code: 'Germany', label: 'Germany' },
    { code: 'Ghana', label: 'Ghana' },
    { code: 'Greece', label: 'Greece' },
    { code: 'Grenada', label: 'Grenada' },
    { code: 'Guatemala', label: 'Guatemala' },
    { code: 'Guinea', label: 'Guinea' },
    { code: 'Guinea-Bissau', label: 'Guinea-Bissau' },
    { code: 'Guyana', label: 'Guyana' },
    { code: 'Haiti', label: 'Haiti' },
    { code: 'Honduras', label: 'Honduras' },
    { code: 'Hungary', label: 'Hungary' },
    { code: 'Iceland', label: 'Iceland' },
    { code: 'India', label: 'India' },
    { code: 'Indonesia', label: 'Indonesia' },
    { code: 'Iran', label: 'Iran' },
    { code: 'Iraq', label: 'Iraq' },
    { code: 'Ireland', label: 'Ireland' },
    { code: 'Israel', label: 'Israel' },
    { code: 'Italy', label: 'Italy' },
    { code: 'Jamaica', label: 'Jamaica' },
    { code: 'Japan', label: 'Japan' },
    { code: 'Jordan', label: 'Jordan' },
    { code: 'Kazakhstan', label: 'Kazakhstan' },
    { code: 'Kenya', label: 'Kenya' },
    { code: 'Kiribati', label: 'Kiribati' },
    { code: 'Kuwait', label: 'Kuwait' },
    { code: 'Kyrgyzstan', label: 'Kyrgyzstan' },
    { code: 'Laos', label: 'Laos' },
    { code: 'Latvia', label: 'Latvia' },
    { code: 'Lebanon', label: 'Lebanon' },
    { code: 'Lesotho', label: 'Lesotho' },
    { code: 'Liberia', label: 'Liberia' },
    { code: 'Libya', label: 'Libya' },
    { code: 'Liechtenstein', label: 'Liechtenstein' },
    { code: 'Lithuania', label: 'Lithuania' },
    { code: 'Luxembourg', label: 'Luxembourg' },
    { code: 'Madagascar', label: 'Madagascar' },
    { code: 'Malawi', label: 'Malawi' },
    { code: 'Malaysia', label: 'Malaysia' },
    { code: 'Maldives', label: 'Maldives' },
    { code: 'Mali', label: 'Mali' },
    { code: 'Malta', label: 'Malta' },
    { code: 'Marshall Islands', label: 'Marshall Islands' },
    { code: 'Mauritania', label: 'Mauritania' },
    { code: 'Mauritius', label: 'Mauritius' },
    { code: 'Mexico', label: 'Mexico' },
    { code: 'Micronesia', label: 'Micronesia' },
    { code: 'Moldova', label: 'Moldova' },
    { code: 'Monaco', label: 'Monaco' },
    { code: 'Mongolia', label: 'Mongolia' },
    { code: 'Montenegro', label: 'Montenegro' },
    { code: 'Morocco', label: 'Morocco' },
    { code: 'Mozambique', label: 'Mozambique' },
    { code: 'Myanmar', label: 'Myanmar' },
    { code: 'Namibia', label: 'Namibia' },
    { code: 'Nauru', label: 'Nauru' },
    { code: 'Nepal', label: 'Nepal' },
    { code: 'Netherlands', label: 'Netherlands' },
    { code: 'New Zealand', label: 'New Zealand' },
    { code: 'Nicaragua', label: 'Nicaragua' },
    { code: 'Niger', label: 'Niger' },
    { code: 'Nigeria', label: 'Nigeria' },
    { code: 'Norway', label: 'Norway' },
    { code: 'Oman', label: 'Oman' },
    { code: 'Pakistan', label: 'Pakistan' },
    { code: 'Palau', label: 'Palau' },
    { code: 'Panama', label: 'Panama' },
    { code: 'Papua New Guinea', label: 'Papua New Guinea' },
    { code: 'Paraguay', label: 'Paraguay' },
    { code: 'Peru', label: 'Peru' },
    { code: 'Philippines', label: 'Philippines' },
    { code: 'Poland', label: 'Poland' },
    { code: 'Portugal', label: 'Portugal' },
    { code: 'Qatar', label: 'Qatar' },
    { code: 'Romania', label: 'Romania' },
    { code: 'Russia', label: 'Russia' },
    { code: 'Rwanda', label: 'Rwanda' },
    { code: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
    { code: 'Saint Lucia', label: 'Saint Lucia' },
    { code: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
    { code: 'Samoa', label: 'Samoa' },
    { code: 'San Marino', label: 'San Marino' },
    { code: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
    { code: 'Saudi Arabia', label: 'Saudi Arabia' },
    { code: 'Senegal', label: 'Senegal' },
    { code: 'Serbia', label: 'Serbia' },
    { code: 'Seychelles', label: 'Seychelles' },
    { code: 'Sierra Leone', label: 'Sierra Leone' },
    { code: 'Singapore', label: 'Singapore' },
    { code: 'Slovakia', label: 'Slovakia' },
    { code: 'Slovenia', label: 'Slovenia' },
    { code: 'Solomon Islands', label: 'Solomon Islands' },
    { code: 'Somalia', label: 'Somalia' },
    { code: 'South Africa', label: 'South Africa' },
    { code: 'South Sudan', label: 'South Sudan' },
    { code: 'Spain', label: 'Spain' },
    { code: 'Sri Lanka', label: 'Sri Lanka' },
    { code: 'Sudan', label: 'Sudan' },
    { code: 'Suriname', label: 'Suriname' },
    { code: 'Sweden', label: 'Sweden' },
    { code: 'Switzerland', label: 'Switzerland' },
    { code: 'Syria', label: 'Syria' },
    { code: 'Taiwan', label: 'Taiwan' },
    { code: 'Tajikistan', label: 'Tajikistan' },
    { code: 'Tanzania', label: 'Tanzania' },
    { code: 'Thailand', label: 'Thailand' },
    { code: 'Timor-Leste', label: 'Timor-Leste' },
    { code: 'Togo', label: 'Togo' },
    { code: 'Tonga', label: 'Tonga' },
    { code: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
    { code: 'Tunisia', label: 'Tunisia' },
    { code: 'Turkey', label: 'Turkey' },
    { code: 'Turkmenistan', label: 'Turkmenistan' },
    { code: 'Tuvalu', label: 'Tuvalu' },
    { code: 'Uganda', label: 'Uganda' },
    { code: 'Ukraine', label: 'Ukraine' },
    { code: 'United Arab Emirates', label: 'United Arab Emirates' },
    { code: 'United Kingdom', label: 'United Kingdom' },
    { code: 'United States', label: 'United States' },
    { code: 'Uruguay', label: 'Uruguay' },
    { code: 'Uzbekistan', label: 'Uzbekistan' },
    { code: 'Vanuatu', label: 'Vanuatu' },
    { code: 'Venezuela', label: 'Venezuela' },
    { code: 'Vietnam', label: 'Vietnam' },
    { code: 'Yemen', label: 'Yemen' },
    { code: 'Zambia', label: 'Zambia' },
    { code: 'Zimbabwe', label: 'Zimbabwe' },
];
